### Register
POST http://localhost:8000/api/register
Content-Type: application/json


{
  "name": "testo",
  "email": "test@exa.com",
  "password": "tesot"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json


{
  "email": "test@ex.com",
  "password": "test"
}


#############################################################
####################### MEMES ###############################
#############################################################

### Get all surveys for user
http://localhost:8000/api/survey

### Get single survey
http://localhost:8000/api/survey/id

### Create single survey
POST http://localhost:8000/api/survey/create
Content-Type: application/json

{
  "name": "Survey 1",
  "description": "LIPSUM MAN"
}